export type Place = {id:string;name:string;district:string;x:number;y:number}
export type Choice = {label:string;why:string;next:string}
export type Node = {id:string;title:string;description:string;place:string;scale:'personal'|'street'|'city';minutesLater:number;choices:Choice[]}
export type Story = {title:string;prompt:string;start:string;places:Place[];nodes:Node[]}
// Honest local fixture. Later the app reads the same model from a Sanity dataset.
export const fixture:Story={title:'The missing bench',prompt:'At 8:04, a bench beside the tram stop is gone. What do you do?',start:'bench',places:[
{id:'stop',name:'Moth Street stop',district:'North Arcade',x:18,y:28},{id:'shop',name:'Second Bell Bakery',district:'North Arcade',x:45,y:40},{id:'hall',name:'Lost Things Office',district:'Civic Quarter',x:77,y:23},{id:'park',name:'Rain Garden',district:'East Bank',x:68,y:75}],nodes:[
{id:'bench',title:'A space where a bench used to be',description:'The tram arrives in six minutes. A chalk rectangle marks the pavement. Nobody seems to know who moved the bench.',place:'stop',scale:'personal',minutesLater:0,choices:[{label:'Draw a bench inside the chalk outline',why:'The drawing gives waiting passengers a place to gather, even without a seat.',next:'drawing'},{label:'Ask the bakery if they saw it',why:'The baker watched the removal from across the street.',next:'bakery'}]},
{id:'drawing',title:'A queue draws itself',description:'People add legs, armrests and an impossible cupholder. The tram driver notices that the line now leaves room for wheelchairs.',place:'stop',scale:'street',minutesLater:11,choices:[{label:'Send the sketch to the Lost Things Office',why:'An archivist can turn a temporary drawing into a city request.',next:'office'},{label:'Leave chalk beside the outline',why:'The drawing becomes a public invitation to keep designing.',next:'garden'}]},
{id:'bakery',title:'The receipt with a strange address',description:'The baker says a city van took the bench to the Rain Garden. On the receipt, someone wrote: “Borrowed for a view.”',place:'shop',scale:'street',minutesLater:8,choices:[{label:'Follow the address',why:'You find out what happened to the bench before deciding what to ask for.',next:'garden'},{label:'File a missing-bench report',why:'The office can trace the permit and make the decision visible.',next:'office'}]},
{id:'office',title:'A form becomes a question',description:'The archivist finds a permit: the bench was moved because people asked for shade at the Rain Garden. She opens a public ballot about what each stop needs.',place:'hall',scale:'city',minutesLater:47,choices:[{label:'Read the city notice',why:'The route ends at a decision that residents can inspect.',next:'ballot'}]},
{id:'garden',title:'A seat with a better view',description:'The bench is here, under a young tree. Two neighbors say their old seats were removed last winter. They want the city to count where rest is missing.',place:'park',scale:'street',minutesLater:28,choices:[{label:'Map the missing seats',why:'A map turns one missing bench into a pattern the city can act on.',next:'ballot'}]},
{id:'ballot',title:'The city counts places to rest',description:'The ballot does not promise a perfect city. It asks a narrower question: which blocks lack a safe place to pause?',place:'hall',scale:'city',minutesLater:96,choices:[]}
]}
