'use client'
import {useMemo,useState} from 'react'
import type {Story,Node} from '../data'

type Draft={title:string;text:string;place:string;name:string}
export default function Experience({story}:{story:Story}){
 const [trail,setTrail]=useState<string[]>([story.start])
 const [showModel,setShowModel]=useState(false)
 const [tab,setTab]=useState<'story'|'map'|'ledger'|'make'>('story')
 const [draft,setDraft]=useState<Draft>({title:'',text:'',place:story.places[0]?.id||'',name:''})
 const [submit,setSubmit]=useState<'idle'|'sending'|'done'|'error'>('idle')
 const [error,setError]=useState('')
 const [search,setSearch]=useState('')
 const current=story.nodes.find(n=>n.id===trail[trail.length-1]) as Node
 const place=story.places.find(p=>p.id===current.place)!
 const found=useMemo(()=>story.nodes.filter(n=>n.title.toLowerCase().includes(search.toLowerCase())||n.description.toLowerCase().includes(search.toLowerCase())),[search,story.nodes])
 const visited=new Set(trail)
 const accessible=useMemo(()=>{const set=new Set([story.start]);const queue=[story.start];while(queue.length){const id=queue.shift()!;const n=story.nodes.find(x=>x.id===id);for(const edge of n?.choices||[]){if(!set.has(edge.next)){set.add(edge.next);queue.push(edge.next)}}}return set},[story])
 function go(id:string){if(!accessible.has(id))return;setTrail([...trail,id]);setTab('story');document.getElementById('case')?.scrollIntoView({behavior:'smooth',block:'start'})}
 async function sendDraft(e:React.FormEvent){e.preventDefault();setSubmit('sending');setError('');try{const res=await fetch('/api/contribute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const json=await res.json();if(!res.ok)throw Error(json.error||'Something went wrong');setSubmit('done');setDraft({title:'',text:'',place:story.places[0]?.id||'',name:''})}catch(e){setError(e instanceof Error?e.message:'Try again');setSubmit('error')}}
 return <main>
 <div className="top"><div className="seal">◌</div><div className="dept">THE DEPARTMENT OF<br/><strong>TINY CONSEQUENCES</strong></div><nav className="nav"><a href="#case">Explore</a><a href="#atlas">Atlas</a><a href="#case" onClick={()=>setTab('make')}>Add a scene</a></nav><span className="edition">CASE FILE 001 / A CITY OF ALMOSTS</span></div>
 <section className="intro"><div className="topographic" aria-hidden="true"/><p className="eyebrow">AN INTERACTIVE WORK OF FICTION · POWERED BY STRUCTURED CONTENT</p><h1><span>One</span><span>little thing</span><span><em>changes</em></span><span>everything.</span></h1><p>Follow a missing bench through a city. Take a detour, inspect the chain of consequences, or leave a story of your own.</p><a className="model" href="#case">ENTER THE CITY ↗</a></section>
 <section className="stats"><div><b>{story.places.length.toString().padStart(2,'0')}</b><span>PLACES TO EXPLORE</span></div><div><b>{story.nodes.length.toString().padStart(2,'0')}</b><span>STORY MOMENTS</span></div><div><b>{trail.length.toString().padStart(2,'0')}</b><span>STEPS IN YOUR ROUTE</span></div><div><b>{story.nodes.filter(n=>visited.has(n.id)).length.toString().padStart(2,'0')}</b><span>SCENES DISCOVERED</span></div></section>
 <section className="invitation"><span className="eyebrow">01 / YOUR STORY STARTS HERE</span><h2>There is no right route.<br/><em>Just what happens next.</em></h2><p>Choose an action to follow the story. Open the atlas to jump between scenes, or use the ledger to see why each turn happened.</p></section>
 <section id="case" className="explorer"><div className="explorer-head"><span>THE MISSING BENCH <i>●</i> LIVE CASE FILE</span><span>DAY 01 · MINUTE {String(current.minutesLater).padStart(2,'0')}</span></div><div className="tabs" role="tablist" aria-label="Explore the story"><button role="tab" aria-selected={tab==='story'} onClick={()=>setTab('story')}>01 / STORY</button><button role="tab" aria-selected={tab==='map'} onClick={()=>setTab('map')}>02 / CITY MAP</button><button role="tab" aria-selected={tab==='ledger'} onClick={()=>setTab('ledger')}>03 / CONSEQUENCE LEDGER</button><button role="tab" aria-selected={tab==='make'} onClick={()=>setTab('make')}>04 / YOUR OWN SCENE</button></div>
 {tab==='story'&&<div className="story-layout"><div className="story-overview"><p className="eyebrow">{place.district} / {current.scale.toUpperCase()} EFFECT</p><h2>{current.title}</h2><p>{current.description}</p><div className="turn-meta"><span>LOCATION<br/><strong>{place.name}</strong></span><span>ELAPSED<br/><strong>{current.minutesLater} MIN</strong></span></div><div className="route-preview">YOUR ROUTE: {trail.map((id,i)=><button key={i} onClick={()=>setTrail(trail.slice(0,i+1))}>{i+1}. {story.nodes.find(n=>n.id===id)?.title}</button>)}</div></div><div className="story-actions"><span className="eyebrow">PICK THE NEXT RIPPLE</span>{current.choices.map((c,i)=><button className="choice" key={c.next+i} onClick={()=>go(c.next)}><small>0{i+1} / THE ACTION</small><b>{c.label}</b><span>BECAUSE: {c.why}</span><em>↗</em></button>)}<div className="story-tools"><button onClick={()=>{setTrail([story.start]);setTab('story')}}>START OVER ↺</button>{trail.length>1&&<button onClick={()=>setTrail(trail.slice(0,-1))}>STEP BACK ←</button>}<button onClick={()=>setTab('map')}>OPEN THE MAP ↗</button></div></div></div>}
 {tab==='map'&&<div className="map-layout"><div className="map"><div className="grid"/><div className="road r1"/><div className="road r2"/><div className="river"/>{story.places.map(p=><button className={'marker '+(p.id===current.place?'active':'')} key={p.id} style={{left:`${p.x}%`,top:`${p.y}%`}} onClick={()=>{const scene=story.nodes.find(n=>n.place===p.id&&accessible.has(n.id));if(scene)go(scene.id)}}><span>✳</span><small>{p.name}</small></button>)}<div className="maplabel">THE CITY OF ALMOSTS<br/>NOT TO SCALE</div></div><div className="map-sidebar"><span className="eyebrow">EXPLORE THE DISTRICTS</span><h2>Every place has a story.</h2><p>Choose a pin, then follow what happens there. Pins take you to a connected scene.</p>{story.places.map(p=><button key={p.id} onClick={()=>{const scene=story.nodes.find(n=>n.place===p.id&&accessible.has(n.id));if(scene)go(scene.id)}}><strong>{p.name}</strong><span>{p.district} / {story.nodes.filter(n=>n.place===p.id).length} {story.nodes.filter(n=>n.place===p.id).length===1?'scene':'scenes'} ↗</span></button>)}</div></div>}
 {tab==='ledger'&&<div className="ledger"><div className="ledger-intro"><span className="eyebrow">THE CONSEQUENCE LEDGER</span><h2>Nothing happens<br/>for no reason.</h2><p>Every choice is a link between structured scenes. Search the whole case file or retrace the route you made.</p><input aria-label="Search scenes" placeholder="Search a scene or detail..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="ledger-list">{found.map((n,i)=><button key={n.id} onClick={()=>go(n.id)}><small>{String(i+1).padStart(2,'0')} / {story.places.find(p=>p.id===n.place)?.name} / +{n.minutesLater} MIN</small><strong>{n.title}</strong><span>{n.description}</span><em>{visited.has(n.id)?'VISITED':'EXPLORE'} ↗</em></button>)}{!found.length&&<p>No scenes match that search.</p>}</div></div>}
 {tab==='make'&&<div id="make" className="make-layout"><div><span className="eyebrow">THE CITY IS STILL BEING WRITTEN</span><h2>What little thing<br/>would you change?</h2><p>Leave a scene for this city. It goes into an editorial draft queue in Sanity, not straight onto the public map. A person reviews it before it becomes part of the story. No account needed; don't include private information.</p><div className="stamp">YOUR SCENE → SANITY DRAFT → HUMAN REVIEW → POSSIBLE PUBLICATION</div></div><form onSubmit={sendDraft}><label>YOUR SCENE TITLE<input maxLength={80} required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="The streetlight that blinked twice"/></label><label>WHERE DOES IT HAPPEN?<select value={draft.place} onChange={e=>setDraft({...draft,place:e.target.value})}>{story.places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>WHAT HAPPENS?<textarea maxLength={700} minLength={30} required value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})} placeholder="Write a small event and what it changes..."/><small>{draft.text.length}/700</small></label><label>NAME (OPTIONAL)<input maxLength={40} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="How should we credit you?"/></label><button type="submit" disabled={submit==='sending'}>{submit==='sending'?'SENDING...':'SEND TO THE DRAFT DESK ↗'}</button>{submit==='done'&&<p role="status" className="success">Received. Your scene is in the review queue, not public yet.</p>}{submit==='error'&&<p role="alert" className="error">{error}</p>}</form></div>}
 </section>
 <section id="atlas" className="atlas"><span className="eyebrow">02 / THE CITY AT A GLANCE</span><h2>Nine moments.<br/>Your route is one of many.</h2><div className="atlas-grid">{story.nodes.map((n,i)=><button key={n.id} onClick={()=>{go(n.id)}}><small>{String(i+1).padStart(2,'0')} / {n.scale.toUpperCase()}</small><b>{n.title}</b><span>{story.places.find(p=>p.id===n.place)?.name} ↗</span></button>)}</div></section>
 <section className="structure"><div><span className="eyebrow">03 / UNDER THE SURFACE</span><h2>Not a generated story.<br/>A living content graph.</h2></div><div><p>Every scene, place and decision is a Sanity document or linked object. Editorial states keep visitor ideas private until reviewed. The app queries published scenes at request time and filters out links to unpublished scenes.</p><button onClick={()=>setShowModel(!showModel)}>{showModel?'CLOSE':'INSPECT'} THE STRUCTURE ↗</button>{showModel&&<div className="schema-note"><p><b>PLACE</b> / name, district, map coordinates</p><p><b>CONSEQUENCE</b> / scene, place, elapsed time, scale, editorial state</p><p><b>CHOICE</b> / label, reason, linked next consequence</p><p><b>VISITOR SCENE</b> / private draft, moderated before publishing</p></div>}</div></section>
 <footer><span>✳ FICTION, NOT A CIVIC FORECAST.</span><span>PROTOTYPE / PATH TWO / DEV x SANITY CHALLENGE</span></footer>
 </main>
}
