'use client'
import {useMemo,useState} from 'react'
import type {Story,Node} from '../data'

type Draft={title:string;text:string;place:string;name:string}
export default function Experience({story}:{story:Story}){
 const [trail,setTrail]=useState<string[]>([story.start])
 const [showModel,setShowModel]=useState(false)
 const [tab,setTab]=useState<'story'|'map'|'ledger'|'make'>('story')
 const [draft,setDraft]=useState<Draft>({title:'',text:'',place:story.places[0]?.id||'',name:''})
 const [submit,setSubmit]=useState<'idle'|'sending'|'done'|'error'>('idle')
 const [error,setError]=useState('')
 const [search,setSearch]=useState('')
 const [pulse,setPulse]=useState(0)
 const current=story.nodes.find(n=>n.id===trail[trail.length-1]) as Node
 const place=story.places.find(p=>p.id===current.place)!
 const found=useMemo(()=>story.nodes.filter(n=>n.title.toLowerCase().includes(search.toLowerCase())||n.description.toLowerCase().includes(search.toLowerCase())),[search,story.nodes])
 const visited=new Set(trail)
 const afterDark=current.minutesLater>=100
 const graphEdges=story.nodes.flatMap(n=>n.choices.map(c=>({from:n,to:story.nodes.find(x=>x.id===c.next)}))).filter((e):e is {from:Node;to:Node}=>!!e.to)
 const routeEdges=trail.slice(1).map((id,i)=>`${trail[i]}:${id}`)
 const accessible=useMemo(()=>{const set=new Set([story.start]);const queue=[story.start];while(queue.length){const id=queue.shift()!;const n=story.nodes.find(x=>x.id===id);for(const edge of n?.choices||[]){if(!set.has(edge.next)){set.add(edge.next);queue.push(edge.next)}}}return set},[story])
 function go(id:string){if(!accessible.has(id))return;setTrail([...trail,id]);setPulse(p=>p+1);setTab('story');document.getElementById('case')?.scrollIntoView({behavior:'smooth',block:'start'})}
 async function sendDraft(e:React.FormEvent){e.preventDefault();setSubmit('sending');setError('');try{const res=await fetch('/api/contribute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const json=await res.json();if(!res.ok)throw Error(json.error||'Something went wrong');setSubmit('done');setDraft({title:'',text:'',place:story.places[0]?.id||'',name:''})}catch(e){setError(e instanceof Error?e.message:'Try again');setSubmit('error')}}
 return <main>
 <div className="top"><div className="seal">◌</div><div className="dept">THE DEPARTMENT OF<br/><strong>TINY CONSEQUENCES</strong></div><nav className="nav"><a href="#case">Explore</a><a href="#atlas">Atlas</a><a href="#case" onClick={()=>setTab('make')}>Add a scene</a></nav><span className="edition">CASE FILE 001 / A CITY OF ALMOSTS</span></div>
 <section className="intro"><div className="topographic" aria-hidden="true"/><p className="eyebrow">AN INTERACTIVE WORK OF FICTION · POWERED BY STRUCTURED CONTENT</p><h1><span>A city</span><span>that</span><span><em>remembers</em></span><span>you.</span></h1><p>One bench disappears. The choices you make leave marks on the map. Follow a consequence across town, then leave a scene for a future visitor to discover after review.</p><a className="model" href="#case">ENTER THE CITY ↗</a></section>
 <section className="stats"><div><b>{story.places.length.toString().padStart(2,'0')}</b><span>PLACES TO EXPLORE</span></div><div><b>{story.nodes.length.toString().padStart(2,'0')}</b><span>STORY MOMENTS</span></div><div><b>{trail.length.toString().padStart(2,'0')}</b><span>STEPS IN YOUR ROUTE</span></div><div><b>{story.nodes.filter(n=>visited.has(n.id)).length.toString().padStart(2,'0')}</b><span>SCENES DISCOVERED</span></div></section>
 <section className="invitation"><span className="eyebrow">01 / YOUR STORY STARTS HERE</span><h2>Every choice leaves<br/><em>something behind.</em></h2><p>Choose an action. Watch its path travel across the city. The map traces your route; the ledger remembers why it happened.</p></section>
 <section id="case" className="explorer"><div className="explorer-head"><span>THE MISSING BENCH <i>●</i> LIVE CASE FILE</span><span>{afterDark?'AFTER DARK':'DAYLIGHT'} · +{String(current.minutesLater).padStart(3,'0')} MIN</span></div><div className="tabs" role="tablist" aria-label="Explore the story"><button role="tab" aria-selected={tab==='story'} onClick={()=>setTab('story')}>01 / STORY</button><button role="tab" aria-selected={tab==='map'} onClick={()=>setTab('map')}>02 / CITY MAP</button><button role="tab" aria-selected={tab==='ledger'} onClick={()=>setTab('ledger')}>03 / CONSEQUENCE LEDGER</button><button role="tab" aria-selected={tab==='make'} onClick={()=>setTab('make')}>04 / YOUR OWN SCENE</button></div>
 {tab==='story'&&<div className="story-layout"><div className="story-overview"><p className="eyebrow">{place.district} / {current.scale.toUpperCase()} EFFECT</p><h2>{current.title}</h2><p>{current.description}</p><div className="ripple-note" key={pulse}><span>THIS CHANGES THE CITY ↗</span><strong>{current.ripple}</strong></div><div className="turn-meta"><span>LOCATION<br/><strong>{place.name}</strong></span><span>ELAPSED<br/><strong>{current.minutesLater} MIN</strong></span></div><div className="route-preview">YOUR ROUTE: {trail.map((id,i)=><button key={i} onClick={()=>setTrail(trail.slice(0,i+1))}>{i+1}. {story.nodes.find(n=>n.id===id)?.title}</button>)}</div></div><div className="story-actions"><span className="eyebrow">PICK THE NEXT RIPPLE</span>{current.choices.map((c,i)=><button className="choice" key={c.next+i} onClick={()=>go(c.next)}><small>0{i+1} / THE ACTION</small><b>{c.label}</b><span>BECAUSE: {c.why}</span><em>↗</em></button>)}<div className="story-tools"><button onClick={()=>{setTrail([story.start]);setTab('story')}}>START OVER ↺</button>{trail.length>1&&<button onClick={()=>setTrail(trail.slice(0,-1))}>STEP BACK ←</button>}<button onClick={()=>setTab('map')}>OPEN THE MAP ↗</button></div></div></div>}
 {tab==='map'&&<div className="map-layout"><div className={'map '+(afterDark?'night-map':'')}><div className="grid"/><div className="road r1"/><div className="road r2"/><div className="river"/><svg className="city-graph" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="arr" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="none" stroke="currentColor"/></marker></defs>{graphEdges.map((e,i)=>{const a=story.places.find(p=>p.id===e.from.place)!,b=story.places.find(p=>p.id===e.to.place)!;const active=routeEdges.includes(`${e.from.id}:${e.to.id}`);if(a.id===b.id)return null;return <path key={i} className={active?'graph-route':'graph-link'} d={`M${a.x*10},${a.y*6} Q${(a.x+b.x)*5},${Math.min(a.y,b.y)*6-28-i%3*7} ${b.x*10},${b.y*6}`} markerEnd={active?'url(#arr)':undefined}/>})}</svg><div className="map-event" key={pulse}><span>{afterDark?'NIGHT ROUTE':'DAYLIGHT ROUTE'} · {trail.length} {trail.length===1?'STEP':'STEPS'}</span><strong>{current.ripple}</strong></div>{story.places.map(p=><button className={'marker '+(p.id===current.place?'active':'')+(trail.some(id=>story.nodes.find(n=>n.id===id)?.place===p.id)?' visited':'')} key={p.id} style={{left:`${p.x}%`,top:`${p.y}%`}} onClick={()=>{const scene=story.nodes.find(n=>n.place===p.id&&accessible.has(n.id));if(scene)go(scene.id)}}><span>✳</span><small>{p.name}</small></button>)}<div className="maplabel">THE CITY OF ALMOSTS<br/>NOT TO SCALE</div></div><div className="map-sidebar"><span className="eyebrow">EXPLORE THE DISTRICTS</span><h2>Every place has a story.</h2><p>The faint lines are possible consequences. Your route lights up in red as decisions carry you between places. Choose a pin to continue.</p><div className="map-key"><span>● YOUR CURRENT PLACE</span><span>━ THE ROUTE YOU MADE</span><span>· POSSIBLE CONNECTIONS</span></div>{story.places.map(p=><button key={p.id} onClick={()=>{const scene=story.nodes.find(n=>n.place===p.id&&accessible.has(n.id));if(scene)go(scene.id)}}><strong>{p.name}</strong><span>{p.district} / {story.nodes.filter(n=>n.place===p.id).length} {story.nodes.filter(n=>n.place===p.id).length===1?'scene':'scenes'} ↗</span></button>)}</div></div>}
 {tab==='ledger'&&<div className="ledger"><div className="ledger-intro"><span className="eyebrow">THE CONSEQUENCE LEDGER</span><h2>Nothing happens<br/>for no reason.</h2><p>Every choice is a link between structured scenes. Search the whole case file or retrace the route you made.</p><input aria-label="Search scenes" placeholder="Search a scene or detail..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="ledger-list">{found.map((n,i)=><button key={n.id} onClick={()=>go(n.id)}><small>{String(i+1).padStart(2,'0')} / {story.places.find(p=>p.id===n.place)?.name} / +{n.minutesLater} MIN</small><strong>{n.title}</strong><span>{n.description}</span><em>{visited.has(n.id)?'VISITED':'EXPLORE'} ↗</em></button>)}{!found.length&&<p>No scenes match that search.</p>}</div></div>}
 {tab==='make'&&<div id="make" className="make-layout"><div><span className="eyebrow">THE CITY IS STILL BEING WRITTEN</span><h2>What little thing<br/>would you change?</h2><p>Leave a scene for this city. It goes into an editorial draft queue in Sanity, not straight onto the public map. A person reviews it before it becomes part of the story. No account needed; don't include private information.</p><div className="stamp">YOUR SCENE → SANITY DRAFT → HUMAN REVIEW → POSSIBLE PUBLICATION</div></div><form onSubmit={sendDraft}><label>YOUR SCENE TITLE<input maxLength={80} required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="The streetlight that blinked twice"/></label><label>WHERE DOES IT HAPPEN?<select value={draft.place} onChange={e=>setDraft({...draft,place:e.target.value})}>{story.places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>WHAT HAPPENS?<textarea maxLength={700} minLength={30} required value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})} placeholder="Write a small event and what it changes..."/><small>{draft.text.length}/700</small></label><label>NAME (OPTIONAL)<input maxLength={40} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="How should we credit you?"/></label><button type="submit" disabled={submit==='sending'}>{submit==='sending'?'SENDING...':'SEND TO THE DRAFT DESK ↗'}</button>{submit==='done'&&<p role="status" className="success">Received. Your scene is in the review queue, not public yet.</p>}{submit==='error'&&<p role="alert" className="error">{error}</p>}</form></div>}
 </section>
 <section id="atlas" className="atlas"><span className="eyebrow">02 / THE CITY AT A GLANCE</span><h2>{story.nodes.length} moments.<br/>Your route is one of many.</h2><div className="atlas-grid">{story.nodes.map((n,i)=><button key={n.id} onClick={()=>{go(n.id)}}><small>{String(i+1).padStart(2,'0')} / {n.scale.toUpperCase()}</small><b>{n.title}</b><span>{story.places.find(p=>p.id===n.place)?.name} ↗</span></button>)}</div></section>
 <section className="visitor-wall"><span className="eyebrow">03 / THE CITY REMEMBERS</span><h2>Made by someone<br/>who came before you.</h2><p>Visitor scenes appear here only after a human editor publishes them in Sanity. The draft desk never posts directly to the public city.</p>{story.visitorScenes.length?<div className="visitor-grid">{story.visitorScenes.map(v=><article key={v.id}><small>{story.places.find(p=>p.id===v.place)?.name} / CONTRIBUTED BY {v.contributor||'Anonymous'}</small><h3>{v.title}</h3><p>{v.description}</p></article>)}</div>:<div className="empty-city">The city is waiting for its first approved visitor scene. Yours could be the beginning. <button onClick={()=>{setTab('make');document.getElementById('case')?.scrollIntoView({behavior:'smooth'})}}>WRITE A SCENE ↗</button></div>}</section><section className="structure"><div><span className="eyebrow">04 / UNDER THE SURFACE</span><h2>Not a generated story.<br/>A living content graph.</h2></div><div><p>Every scene, place and decision is a Sanity document or linked object. A ripple belongs to a Sanity consequence, and choices reference the next consequence. Visitor submissions become private drafts; a human editor publishes them before they appear in the public city. The app queries only published scenes and filters links to unpublished records.</p><button onClick={()=>setShowModel(!showModel)}>{showModel?'CLOSE':'INSPECT'} THE STRUCTURE ↗</button>{showModel&&<div className="schema-note"><p><b>PLACE</b> / name, district, map coordinates</p><p><b>CONSEQUENCE</b> / scene, place, elapsed time, scale, visible ripple, editorial state</p><p><b>CHOICE</b> / label, reason, linked next consequence</p><p><b>VISITOR SCENE</b> / private draft, editor note, moderated publication</p></div>}</div></section>
 <footer><span>✳ FICTION, NOT A CIVIC FORECAST.</span><span>INTERACTIVE FICTION / DEV x SANITY CHALLENGE</span></footer>
 </main>
}
